<?php

/**
 * @file
 * Xatkit module file.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function xatkit_theme($existing, $type, $theme, $path) {
  return [
    'xatkit' => [
      'template' => 'xatkit-display',
      'variables' => [
        'variables' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_help().
 */
function xatkit_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.xatkit':
      $text = file_get_contents(__DIR__ . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}
